Valentina
suicaed/tourandtravel_site pull request #2
Opened 2021-11-12 14:29 UTC by ValentinaBrigantina

2021-11-12 17:12 UTC, suicaed commented on assets/styles/components/secondscreen.css
> +    justify-content: space-around;
We don't need any additional space around section.

2021-11-12 17:13 UTC, suicaed commented on assets/styles/components/secondscreen.css
> +    margin: 0;
Disable the margin in reset.css

2021-11-12 17:15 UTC, suicaed commented on assets/styles/components/secondscreen.css
> +    margin: 0;
Describe <h2> styles in common.css
Use rem in font-size.

2021-11-12 17:15 UTC, suicaed commented on assets/styles/components/secondscreen.css
> +    font-size: 17px;
Use rem instead of px.

2021-11-12 17:16 UTC, suicaed commented on assets/styles/components/secondscreen.css
> +    line-height: 30px;
Rem.

2021-11-12 17:18 UTC, suicaed commented on index.html
> +          <div class="article-info__text">
There is no need in div wrapper, just use <p> with a class.

2021-11-12 17:19 UTC, suicaed commented on index.html
> +          <div class="article-info__text">
There is no need in div wrapper, just use with a class.

2021-11-12 17:21 UTC, suicaed commented on assets/img/element.svg
> +<svg width="17" height="17" viewBox="0 0 17 17" fill="none" xmlns="http://www.w3.org/2000/svg">
What it is used for? Remove unnecessary files.

2021-11-12 17:22 UTC, suicaed commented on assets/img/element2.svg
> +<svg width="21" height="21" viewBox="0 0 21 21" fill="none" xmlns="http://www.w3.org/2000/svg">
Unnecessary file.

2021-11-12 17:22 UTC, suicaed commented on assets/img/element3.svg
> +<svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
Unnecessary file.

2021-11-12 17:23 UTC, suicaed commented on assets/styles/components/secondscreen.css
> +    margin: auto;
margin auto will not work here.

2021-11-12 17:31 UTC, suicaed commented on assets/styles/components/secondscreen.css
> +    display: flex;
Surely we don't need flexbox here.

2021-11-12 17:31 UTC, suicaed commented on assets/styles/components/secondscreen.css
> +    font-size: 36px;
Use relative font size - rem.

2021-11-12 17:35 UTC, suicaed requested changes
See comments. Make some changes.
Overall, not bad.
Don't worry, comments is a good stuff. They makes your code better. Code review is a study.

2021-11-12 21:20 UTC, ValentinaBrigantina commented
👍

2021-11-13 12:54 UTC, suicaed approved these changes

2021-11-13 12:55 UTC, merged